language: python

python:
  - '2.7'

cache: pip

sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential git cmake
    # http://pyside.readthedocs.io/en/latest/building/linux.html
  - sudo apt-get install libqt4-dev libxml2-dev libxslt1-dev libqtwebkit-dev libqt4-sql-sqlite
  - sudo apt-get install -y xvfb

install:
  - pip install -U pip setuptools wheel
  - pip install -U tox tox-travis
  - pip install pyside pytest pytest-qt python-xlib

script:
  - xvfb-run pytest --verbose
