language: python

python:
  - '2.7'

before_install:
  - sudo apt-get -qq update
  - pip install wheel
  # http://pyside.readthedocs.io/en/latest/building/linux.html
  - sudo apt-get install build-essential git cmake libqt4-dev libxml2-dev libxslt1-dev libqtwebkit-dev
  - sudo apt-get install -y python-pyside

script:
  - python -c "from PySide.QtGui import *"
  - tox