language: python

python:
  - '2.7'

cache: pip

sudo: required

before_install:
  - sudo apt-get -qq update
  # http://pyside.readthedocs.io/en/latest/building/linux.html
  - sudo apt-get install -y sqlite3 libsqlite3-dev
  - sudo apt-get install -y build-essential git cmake libqt4-dev libxml2-dev libxslt1-dev libqtwebkit-dev
  - sudo apt-get install -y xvfb
  - sudo apt-get install -y python-pyside

install:
  - pip install -U pip setuptools wheel
  - pip install -U tox tox-travis
  - pip install pyside pytest pytest-qt python-xlib

script:
  - xvfb-run pytest --verbose
