Document: clipmanager
Title: Debian clipmanager Manual
Author: <insert document author here>
Abstract: This manual describes what clipmanager is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/clipmanager/clipmanager.sgml.gz

Format: postscript
Files: /usr/share/doc/clipmanager/clipmanager.ps.gz

Format: text
Files: /usr/share/doc/clipmanager/clipmanager.text.gz

Format: HTML
Index: /usr/share/doc/clipmanager/html/index.html
Files: /usr/share/doc/clipmanager/html/*.html
