__title__ = 'ClipManager'
__version__ = '0.3'
__author__ = 'Scott Werner'
__license__ = 'BSD'
__copyright__ = 'Copyright 2018 Scott Werner'
__org__ = 'Werner'
__email__ = 'scott.werner.vt@gmail.com'
__description__ = 'Manage the system\'s clipboard history.'
__url__ = 'https://github.com/scottwernervt/clipmanager/'

